import fs from 'node:fs';

const path = 'server/linkedinConferenceActivityBootstrap.ts';
let source = fs.readFileSync(path, 'utf8');

// Final avatar recovery pass. This intentionally runs after every earlier LinkedIn avatar patch.
// It searches the returned post records recursively because HarvestAPI has used multiple shapes
// over time (author, actor, owner, postedBy, nested avatar/photo objects, etc.). A portrait is
// accepted only when it is a LinkedIn person-photo URL and is tied to the requested member by
// exact profile slug/publicIdentifier, exact post-owner slug, or exact first+last name match.

source = source.replace(
  'SELECT id, linkedin_url FROM users WHERE id = ?',
  'SELECT id, linkedin_url, name FROM users WHERE id = ?',
);

const anchor = '  const { conferenceActivity, callsForPapers } = classifyPosts(posts, requestedUrl);';
const marker = '  // FINAL_RECURSIVE_LINKEDIN_AVATAR';
if (!source.includes(anchor)) {
  throw new Error('[linkedin-avatar-recursive-final] classify anchor not found');
}

if (!source.includes(marker)) {
  const block = [
    '  // FINAL_RECURSIVE_LINKEDIN_AVATAR',
    '  const finalRequestedSlug = profileSlug(requestedUrl);',
    '  const normalizeFinalAvatarName = (value: unknown) => clean(value).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();',
    '  const finalMemberName = normalizeFinalAvatarName(user.name);',
    '  const finalMemberParts = finalMemberName.split(/\\s+/).filter(Boolean);',
    '  const finalMemberFirst = finalMemberParts[0] || "";',
    '  const finalMemberLast = finalMemberParts[finalMemberParts.length - 1] || "";',
    '',
    '  const isFinalPersonPhotoUrl = (value: unknown): value is string => {',
    '    if (typeof value !== "string" || !/^https?:\\/\\//i.test(value.trim())) return false;',
    '    try {',
    '      const url = new URL(value.trim());',
    '      const host = url.hostname.toLowerCase();',
    '      const pathAndQuery = (url.pathname + url.search).toLowerCase();',
    '      return host.endsWith("licdn.com") && /profile-(?:displayphoto|framedphoto)/i.test(pathAndQuery);',
    '    } catch {',
    '      return false;',
    '    }',
    '  };',
    '',
    '  const findFinalPersonPhoto = (node: unknown, depth = 0): string | null => {',
    '    if (depth > 7 || node == null) return null;',
    '    if (isFinalPersonPhotoUrl(node)) return node.trim();',
    '    if (Array.isArray(node)) {',
    '      for (const item of node) {',
    '        const found = findFinalPersonPhoto(item, depth + 1);',
    '        if (found) return found;',
    '      }',
    '      return null;',
    '    }',
    '    if (typeof node !== "object") return null;',
    '    const record = node as Record<string, unknown>;',
    '    const preferredKeys = ["avatar", "photo", "photoUrl", "picture", "pictureUrl", "profilePicture", "profilePictureUrl", "image", "imageUrl", "displayPhoto"];',
    '    for (const key of preferredKeys) {',
    '      if (!(key in record)) continue;',
    '      const found = findFinalPersonPhoto(record[key], depth + 1);',
    '      if (found) return found;',
    '    }',
    '    for (const child of Object.values(record)) {',
    '      const found = findFinalPersonPhoto(child, depth + 1);',
    '      if (found) return found;',
    '    }',
    '    return null;',
    '  };',
    '',
    '  const finalObjectMatchesMember = (value: unknown): boolean => {',
    '    if (!value || typeof value !== "object") return false;',
    '    const record = value as Record<string, any>;',
    '    const type = clean(record.type || record.actorType || record.entityType).toLowerCase();',
    '    if (type && /company|organization|organisation|school|event|page/.test(type)) return false;',
    '    const publicIdentifier = clean(record.publicIdentifier || record.public_id || record.slug || record.universalName).toLowerCase();',
    '    const linkedInSlug = profileSlug(record.linkedinUrl || record.linkedinURL || record.profileUrl || record.profileURL || record.url);',
    '    const name = normalizeFinalAvatarName(record.name || record.fullName || record.full_name || record.displayName);',
    '    const parts = name.split(/\\s+/).filter(Boolean);',
    '    const first = parts[0] || "";',
    '    const last = parts[parts.length - 1] || "";',
    '    const nameMatches = Boolean(finalMemberFirst && finalMemberLast && first === finalMemberFirst && last === finalMemberLast);',
    '    return Boolean(finalRequestedSlug && (publicIdentifier === finalRequestedSlug || linkedInSlug === finalRequestedSlug)) || nameMatches;',
    '  };',
    '',
    '  const findFinalMatchedPortrait = (node: unknown, depth = 0): string | null => {',
    '    if (depth > 6 || node == null) return null;',
    '    if (Array.isArray(node)) {',
    '      for (const item of node) {',
    '        const found = findFinalMatchedPortrait(item, depth + 1);',
    '        if (found) return found;',
    '      }',
    '      return null;',
    '    }',
    '    if (typeof node !== "object") return null;',
    '    const record = node as Record<string, unknown>;',
    '    if (finalObjectMatchesMember(record)) {',
    '      const portrait = findFinalPersonPhoto(record);',
    '      if (portrait) return portrait;',
    '    }',
    '    const identityKeys = ["author", "actor", "owner", "postedBy", "posted_by", "profile", "member", "creator", "person"];',
    '    for (const key of identityKeys) {',
    '      if (!(key in record)) continue;',
    '      const found = findFinalMatchedPortrait(record[key], depth + 1);',
    '      if (found) return found;',
    '    }',
    '    for (const child of Object.values(record)) {',
    '      const found = findFinalMatchedPortrait(child, depth + 1);',
    '      if (found) return found;',
    '    }',
    '    return null;',
    '  };',
    '',
    '  const finalLinkedInPortrait = (() => {',
    '    for (const rawPost of posts) {',
    '      const post = rawPost && typeof rawPost === "object" ? rawPost as Record<string, any> : {};',
    '      const matched = findFinalMatchedPortrait(post);',
    '      if (matched) return matched;',
    '',
    '      // Safe fallback for the exact member\'s own post URL when provider identity fields are sparse.',
    '      if (finalRequestedSlug) {',
    '        try {',
    '          const rawUrl = clean(post.linkedinUrl || post.postUrl || post.url || post.shareUrl);',
    '          const url = new URL(rawUrl);',
    '          const owner = url.pathname.match(/^\\/posts\\/([^_/?#]+)/i)?.[1]?.toLowerCase() || null;',
    '          if (owner === finalRequestedSlug) {',
    '            for (const key of ["author", "actor", "owner", "postedBy", "profile"]) {',
    '              const portrait = findFinalPersonPhoto(post[key]);',
    '              if (portrait) return portrait;',
    '            }',
    '          }',
    '        } catch {',
    '          // Ignore malformed post URLs.',
    '        }',
    '      }',
    '    }',
    '    return null;',
    '  })();',
    '',
    '  if (finalLinkedInPortrait) {',
    '    const avatarRow = await dbGet<any>("SELECT avatar FROM users WHERE id = ?", [userId]);',
    '    const currentAvatar = typeof avatarRow?.avatar === "string" ? avatarRow.avatar.trim() : "";',
    '    const canAutoFill = !currentAvatar || currentAvatar.startsWith("data:image/svg+xml") || currentAvatar.length < 12;',
    '    if (canAutoFill) {',
    '      let avatarValue = finalLinkedInPortrait;',
    '      const pictureController = new AbortController();',
    '      const pictureTimeout = setTimeout(() => pictureController.abort(), 12_000);',
    '      try {',
    '        const pictureResponse = await fetch(finalLinkedInPortrait, {',
    '          signal: pictureController.signal,',
    '          headers: {',
    '            Accept: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",',
    '            "User-Agent": "Mozilla/5.0 ConferenceGate LinkedIn Final Avatar",',
    '          },',
    '        });',
    '        const contentType = (pictureResponse.headers.get("content-type") || "").split(";")[0].trim().toLowerCase();',
    '        if (pictureResponse.ok && contentType.startsWith("image/")) {',
    '          const bytes = Buffer.from(await pictureResponse.arrayBuffer());',
    '          if (bytes.length > 0 && bytes.length <= 1_500_000) {',
    '            avatarValue = "data:" + contentType + ";base64," + bytes.toString("base64");',
    '          }',
    '        }',
    '      } catch {',
    '        // Keep LinkedIn CDN URL if direct caching is blocked.',
    '      } finally {',
    '        clearTimeout(pictureTimeout);',
    '      }',
    '      await dbRun("UPDATE users SET avatar = ? WHERE id = ?", [avatarValue, userId]);',
    '      console.log("[linkedin-avatar-recursive-final] imported exact member portrait");',
    '    }',
    '  } else {',
    '    console.log("[linkedin-avatar-recursive-final] no exact member portrait found in returned posts");',
    '  }',
  ].join('\n');
  source = source.replace(anchor, block + '\n\n' + anchor);
}

fs.writeFileSync(path, source);
console.log('[linkedin-avatar-recursive-final] recursive member portrait recovery installed last');
